config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'posts#index'

  resources :posts, only: [:new, :create, :show] do
  	member do
  		put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
  	end
  	resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
    validates :body, presence: true
    # validates :title, :image_url, :presence => true

	default_scope -> {order(created_at: :desc)}

	auto_html_for :body do
    html_escape
    image
    youtube(:width => 400, :height => 250, :autoplay => true)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments
	validates :title, :image_url, :presence => true
	
	default_scope -> {order(created_at: :desc)}

	auto_html_for :image_url do
	    html_escape
	    image
	    link :target => "_blank", :rel => "nofollow"
	    simple_format
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include AutoHtml
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(comment_params)
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

		if @comment.save
			flash[:success] = 'Comment Posted'
			redirect_to post_path(@post)
		else
			flash[:error] = 'Something Went Wrong'
			redirect_to post_path(@post)
		end
	end

	private

		def comment_params
			params.require(:comment).permit(:body)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :upvote, :downvote]
	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			flash[:success] = 'Post Success!'
			redirect_to root_path
		else
			flash[:error] = 'Something went wrong'
			render :new
		end
	end

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
		@comments = Comment.where(post_id: @post)
	end

	def upvote
		@post = Post.find(params[:id])

		if @post.save
			@post.upvote_by current_user
			flash[:success] = "Upvoted"
		else
			flash[:error] = "Please Sign In"
		end
		redirect_to :back
	end

	def downvote
		@post = Post.find(params[:id])

		if @post.save
			@post.downvote_by current_user
			flash[:success] = "Downvoted"
		else
			flash[:error] = "Please Sign In"
		end
		redirect_to :back
	end

	private

		def post_params
			params.require(:post).permit(:title, :image_url, :content)
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def root
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comments.html.erb
<% @comments.each do |comment| %>
	<div class="comment">

		<div class="comment-name">
			<span><%= comment.user.username %></span> -
			<span class="date" ><%= time_ago_in_words(comment.created_at) %> ago</span>
		</div>

		<% if comment.body_html.present? %>
			<div class="comment-html">
				<%= comment.body_html %>
			</div>
		<% else %>
			<%= comment.body %>
		<% end %>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <%= f.text_area :body, placeholder: 'Comment' %>
  <%= f.submit 'Post' %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <div class="logo"><%= link_to 'Derp', root_path %></div>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">Menu</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to "New", new_post_path %></li>
          <li class="nav-link"><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="nav-link"><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImgurClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 	
		<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |message_type, message| %>
			<div id="flash" class="flash-<%= message_type %>"><%= message %></div>
		<% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/posts/index.html.erb
<div class="posts">
	<% @posts.each do |post| %>
		
			<div class="post hover-tile-outer" style="background-image: url(<%= post.image_url %>)">
				<div class="hover-tile-container">
			    <div class="hover-tile hover-tile-visible"></div>
			    <div class="hover-tile hover-tile-hidden">
			    	<div class="posts-title">
			    		<%= link_to post_path(post), method: :get do %>
				      	<h4><%= post.title %></h4>
				      <% end %>
			    	</div>
			      
			      <div class="vote">
			      	<%= link_to like_post_path(post), method: :put, class: 'up' do %>
							<span><i class="fa fa-chevron-up"></i></span>
							<% end %>
							<%= link_to dislike_post_path(post), method: :put, class: 'down' do %>
								<span><i class="fa fa-chevron-down"></i></span>
							<% end %>
			      </div>
			      <p><%= post.get_upvotes.size %> points</p>
			    </div>
			  </div>
			</div>
		
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="form-bigbox">
  <div class="form-box">
		<%= form_for :post, url: posts_path do |f| %>
		    
		    <%= f.text_field :title, placeholder: "Title", class: 'form-control' %>
		    <br>
		    <%= f.text_field :image_url, placeholder: "Image Url", class: 'form-control' %>
		    <br>
		    <%= f.text_area :content, placeholder: "Content", class: 'form-control' %>
		    <br>
		    <div class="actions">
			  	<%= f.submit "Submit" %>
			  </div>

		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="show-bigbox">
	<div class="show-box">
		<li><h2><%= @post.title %></h2></li>
		<li>
			<%= @post.user.username %> -
			<span class="date"><%= time_ago_in_words(@post.created_at) %> ago</span>
		</li>
		<%= @post.image_url_html %>

		<div class="vote">
    	<%= link_to like_post_path(@post), method: :put, class: 'up' do %>
			<span><i class="fa fa-chevron-up"></i></span>
			<% end %>
			<%= link_to dislike_post_path(@post), method: :put, class: 'down' do %>
				<span><i class="fa fa-chevron-down"></i></span>
			<% end %>
			<span><%= @post.get_upvotes.size %> points</span>
    </div>
	</div>

	<div class="comments-box">
		<%= render 'comments/form' %>
		<%= render 'comments/comments' %>
	</div>
</div>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>